version: '3'

services:
  postgres:
    image: 'postgres:14-bullseye'
    container_name: 'opus-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=1111'
      - 'POSTGRES_DB=jwt_security'
  app:
    build: ./
    container_name: 'opus-app'
    ports:
      - 8080:8080
